
name: Deploy strapi (prod)

on:
  push:
    branches:
      - master
      - develop
    paths:
      - apps/strapi/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # extract branch name to use in deploy
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    # deploy to Heroku
    - uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_PROD_STRAPI }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        branch: ${{ steps.extract_branch.outputs.branch }}
